from pyautogui import *
import time
import os
os.system('clear')
correction = 'ECK' 
dir = f'/home/loki/Research/Ethyl_Propiolate/VTST-{correction}/'

session =  Point(x=98, y=85)
close = Point(x=98, y=188)
open =  Point(x=107, y=136)
temp = Point(x=839, y=120)
tmin = Point(x=921, y=115)
tmax = Point(x=1044, y=115)
step = Point(x=1121, y=117)
k = Point(x=1759, y=218)
datas = Point(x=496, y=176)
kvtst = Point(x=246, y=90)
ktunnel = Point(x=313, y=85)
save_button = Point(x=117, y=145)
data_exit = Point(x=531, y=50)
time.sleep(3)

for state in range(3,15):
    click(session)
    click(close)
    hotkey('enter')
    click(session)
    click(open)
    typewrite(f'{dir}/TS{state}_VTST-ECK.kstp')
    hotkey('enter')
    click(temp)
    hotkey('tab')
    hotkey('ctrl','a')
    typewrite('200')
    hotkey('enter')
    hotkey('tab')
    hotkey('ctrl','a')
    typewrite('500')
    hotkey('enter')
    hotkey('tab')
    hotkey('ctrl','a')
    typewrite('1')
    hotkey('enter')
    click(k)
    click(datas)
    click(kvtst)
    click(save_button)
    typewrite(dir+f'Path{state}_kvtst')
    hotkey('enter')
    click(ktunnel)
    click(save_button)
    typewrite(dir+f'Path{state}_k/tunnel')
    hotkey('enter')
    time.sleep(1)
    click(data_exit)
    break
